openapi: '3.0.3'

info:
  title: CSE183 Books Example
  version: 0.1.0

servers:
  - url: http://localhost:3010

paths:
  /v0/books:
    get:
      description: Returns an array of books
      parameters:
        - in: query
          name: author
          schema:
            type: string
          required: false
          description: Author's name, in part or full
      responses:
        200:
          description: Books Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BooksResponse'
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      description: Creates a new book
      requestBody:
        description: Book to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        201:
          description: Application response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        400:
          description: Invalid ISBN
        409:
          description: Conflict. Requested ISBN in use.
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v0/books/{isbn}:
    get:
      description: Returns a single book
      parameters:
      - name: isbn
        in: path
        description: ISBN of the book
        required: true
        schema:
          type: string
      responses:
        200:
          description: Book found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        400:
          description: Invalid ISBN
        404:
          description: Book not found
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
components:
  schemas:
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

    BooksResponse:
      type: array
      items:
        $ref: '#/components/schemas/Book'

    Book:
      type: object
      additionalProperties: false
      properties:
        isbn:
          type: string
        title:
          type: string
        author:
          type: string
        publisher:
          type: string
      required:
        - isbn 
        - title
        - author 
        - publisher


