
> tRNA | Glu | 7UC | Bos taurus | mitochondrial
GUUCUUGU"GUUGAAUGACAACLAPGGUUU7UCAUAPCAUUAGU?AUGGUPAG"UUCCAUGUAAGAAUACCA
> tRNA | Phe | GAA | Bos taurus | mitochondrial
GUUGAUGU"LCUUAACCCAAAGCAAGGCACUGAAAAPGCCUAGAUGAGUCUCCCAACUCCAUAAACACCA
> tRNA | Gly | UCC | Bos taurus | mitochondrial
AUUCUUUU"LUAUUAACUAGUACAGCUGACUUCCAAPCAGCUAGUUUCGGUCUAGUCCGAAAAAGAAUACCA
> tRNA | Ile | GAU | Bos taurus | mitochondrial
AGAAAUAUKUCUGACAAAAGARPUACAUUGAU6GUGUAAAUAAUAGAGGUUCA"ACCCUCUUAUUUCUACCA
> tRNA | Lys | 7UU | Bos taurus | mitochondrial
CACUAAGA"LCUAUAUAGCACPAACCU7UU6AGUUAGAGAUUGAGAGCCAU"UACUCUCCUUGGUGACCA
> tRNA | Leu | ÊAA | Bos taurus | mitochondrial
GUUAAGGUKLCAGAGCCCGGDAAUUGCAPAAAACUÊAAACPUUUAUAUC?AGAGAUUCA"AUCCUCUCCUUAACACCA
> tRNA | Leu | UAG | Bos taurus | mitochondrial
ACUUUUAA"LGAUAGUAGDUUAUCCLPPGGPCUUAGKAACCAAAAAAUUGGUGCAACUCCAAAUAAAAGUACCA
> tRNA | Arg | UCG | Bos taurus | mitochondrial
UGGUACUU"GUUUAAAAUAAAAUAAAUGAUUUCGACPCAUUAGAUUAUGAUUUAAUUCAUAAUUACCAACCA
> tRNA | Ser | GCU | Bos taurus | mitochondrial
GAAAAAGUAUGCAAGAACUGCU6AUUC_UGCUC?CAUAUCUAAU_UAUGGCUUUUUCGCCA
> tRNA | Ser | UGA | Bos taurus | mitochondrial
GAGAGAGACAUAGAGGDUAUGAPGPPGG'UUGA+ACCAAUAGUAGGGGGUPCG"UUCCUUCCUUUCUUACCA
> tRNA | Thr | UGU | Bos taurus | mitochondrial
GUCUUUGU"GUACAUCUAAUAUACUGGU'UUGU6AACCAGAGAAGGAGAACAACU_CCUCCCPAAGA?UCCA
> tRNA | Val | UAC | Bos taurus | mitochondrial
CAAGAUAU"LCUUAAACAAAGCAPCCAGUUUACACCUAGAAGACUUCAUUCAUUAUGAAUAUCUUGACCA
> tRNA | Trp | ÊCA | Bos taurus | mitochondrial
AGGAAUUU"LGUUAAACAGACCAAGAGCCUÊCA*AGCCCUAAG?AAGUACAAUUUACUUAAUUCCUGCCA
> tRNA | Ini | >AU | Bos taurus | mitochondrial
AGUAAGGUCAGCUAAUUAAGCUAPCGGGCC>AUACCCCGAAAAUGPUGGUUUAUAUCCUUCCCGUACUACCA
> tRNA | Ala | UGC | Bos taurus | mitochondrial
GAGGAUUU"LCUUAAUUAAAGULGPUGAUUUGCAUPCAAUUGAUGUAAGGUGPAGUCUUGCAAUCCUUACCA
> tRNA | Cys | GCA | Bos taurus | mitochondrial
AGCCCUGUKGUGAAUUUACACGPPGAAPUGCA+APUCAGAGAAGCAGCUUCA"UUCUGCCGGGGCUUCCA
> tRNA | Asp | QUC | Bos taurus | mitochondrial
GAGGULUU"GUAAAACAUUAUAPAAUPUUQUCAAAGUUAAGUUACAAGUGAAAGUCCUGUACACCUCACCA
> tRNA | His | QUG | Bos taurus | mitochondrial
GUAAAUAU"LUUUAACAAAAACAPUAGAUUQUGAAPCUAACAAUAGAAACUCAUU_CUUCUUAUUUACCCCA
> tRNA | Asn | QUU | Bos taurus | mitochondrial
UAGAUUGA"LCCAGUUAGCUAGGGUGPPUAGCUQUU6ACUAAAGUUU?GUGGGGGUGGAGCCCACCAGUCUAGCCA
> tRNA | Pro | UGG | Bos taurus | mitochondrial
CAGGGAAU"LUUUAAAUAGAACUPCAGCUUUGGKGGUUGAUGGUGAGACUGCAGUUUCUUCCUUGACCA
> tRNA | Tyr | QUA | Bos taurus | mitochondrial
GGUAAAAUKLCUGAGCAAAGCAUPAGACUQUA*APCUAAAGAUAGAGGUPUGACUCCUCUUUUUACCACCA
> tRNA | Gln | 7UG | Bos taurus | mitochondrial
UAGAAUUUKGUGUAAUUGGGAGCACGAAGAGUU7UGKAPPCUUAGGAGUAGGUPCGAUUCCUAUAGUUCUAGCCA
